'use strict';(function(){function r(a,c){c=10**c;return Math.round(a*c)/c}function w(a,c,e,h){b.lineWidth=3;b.strokeStyle="#000";b.beginPath();b.arc(a,c,7,0,2*Math.PI,!1);b.stroke();b.fill();if(e){b.font="15px Arial";e=b.measureText(h.g||"").width;e+=10;b.fillStyle="#fff";var n=.5*e;a=a-n-3.5;c-=48;b.fillRect(a,c+1,e,22);b.lineWidth=0;e=a+(n-3.5);n=c+22;var z=[[0,0],[10,0],[5,10]];b.beginPath();var x=0,p;for(p of z)0==x?b.moveTo(p[0]+e,p[1]+n):b.lineTo(p[0]+e,p[1]+n),x++;b.closePath();b.fill();b.fillStyle=
"#000";b.fillText(h.g||"",a+5,c+2+11+2)}}function t(a,c){return{x:a*f-g.x+d.width/2,y:c*f-g.y+d.height/2}}const A=[{path:"map/mapmain.png",origin:{x:0,y:0},scale:1},{path:"map/mapexp2.png",origin:{x:-632,y:-213},scale:1.12},{path:"map/mapexp3.png",origin:{x:672,y:-217},scale:1.023},{path:"map/mapexp4.png",origin:{x:30,y:-675},scale:1},{path:"map/mapexp5.png",origin:{x:-576,y:289},scale:.5},{path:"map/mapexp6.png",origin:{x:-821,y:60},scale:1}],B=[{x:70,y:17,g:"furnacejesus"},{x:53,y:-28,g:"ilovefurnaces"},
{x:-10,y:-97,g:"furnacemarx"},{x:109,y:119,g:"comradefurnace",i:!0},{x:-21,y:60,g:"F.P.D",j:!0},{x:-126,y:26,g:"capitalistfurnace"},{x:-122,y:-105,g:"invertedfurnace"},{x:-195,y:-34,g:"americanfurnace"},{x:-330,y:-108,g:"anvilleader"},{x:-470,y:-109,g:"i_eat_wii"},{x:-464,y:-183,g:"i_like_wii"},{x:-361,y:-263,g:"eminem_wii"},{x:-89,y:-221,g:"freezerpresident",i:!0},{x:64,y:-174,g:"fakefurnace"},{x:84,y:-108,g:"comicalylargefreezer"},{x:222,y:-64,g:"furnacekiller"},{x:199,y:35,g:"ikillfurnacesforfun"},
{x:348,y:4,g:"antifurnacegroup"},{x:380,y:-92,g:"femboyfurnace"},{x:197,y:-146,g:"kawaiifurnace",i:!0},{x:201,y:260,g:"handsomefurnace"},{x:-56,y:382,g:"ThaiFurnace",j:!0},{x:-167,y:376,g:"iFurnace",j:!0},{x:-90,y:120,g:"iunfuckfurnaces"},{x:226,y:127,g:"iwillendfurnaces"},{x:135,y:-200,g:"metalfurnace"},{x:-298,y:114,g:"dragonfurnace"},{x:96,y:-309,g:"freezersorcerer"},{x:-599,y:326,g:"eldritchfurnace"},{x:-824,y:85,g:"upsidedownfurnace",i:!0},{x:414,y:-48,g:"furnacekitty"}],C=[{x:-128,y:81,name:"West Burnin"},
{x:22,y:-50,name:"East Burnin"},{x:-296,y:-184,name:"Forgehelm"},{x:-424,y:-228,name:"Wiiland"},{x:-21,y:-233,name:"Glacia"},{x:10,y:-332,name:"Coald Mines"},{x:282,y:7,name:"Pyraxis"},{x:202,y:-174,name:"Ignicis"},{x:0,y:-480,name:"Unclaimed Territories"},{x:-595,y:298,name:"Eldritch Tower"},{x:-834,y:49,name:"Furnacestralia"}],d=document.querySelector("#c"),D=document.querySelector(".cursor-pos");if(null==d)console.error("Failed to get canvas!");else{var b=d.getContext("2d"),g={x:0,y:0},f=1,q=1/
f,u=!1,k=0,l=0,y=[],m={x:null,y:null},v=!1;setInterval(function(){b.translate(.5,.5);d.width=document.documentElement.clientWidth;d.height=document.documentElement.clientHeight;d.style.position="absolute";d.style.left="0";d.style.top="0";b.fillStyle="#C3E7FB";b.fillRect(0,0,d.width,d.height);for(var a of y){var c=a.h.width*a.scale*f;const h=a.h.height*a.scale*f;b.drawImage(a.h,a.origin.x*f-c/2-g.x+d.width/2,a.origin.y*f-h/2-g.y+d.height/2,c,h)}D.innerText="Cursor Position: ("+r((k-d.width/2+g.x)*
q,2)+", "+r((l-d.height/2+g.y)*q,2)+")";for(var e of C)a=e.name||"???",b.font="25px Arial",b.fillStyle="#000",b.strokeStyle="#fff",b.lineWidth=3,c=t(e.x-.5*b.measureText(a).width,e.y),b.strokeText(a,c.x,c.y),b.fillText(a,c.x,c.y);null!=m.x&&null!=m.y&&(b.strokeStyle="#000",b.fillStyle="#f00",e=t(m.x-3.5,m.y-3.5),w(e.x,e.y,7>Math.sqrt((k-e.x)**2+(l-e.y)**2),{g:(m.j?"":"u/")+m.g}));for(const h of B)e=t(h.x-2.5,h.y-2.5),a=5>Math.sqrt((k-e.x)**2+(l-e.y)**2),b.fillStyle=h.i?a?"#ec0":"#fe0":a?"#090":"#0f0",
w(e.x,e.y,a,{g:(h.j?"":"u/")+h.g})},1E3/60);d.style.cursor="grab";d.addEventListener("mousedown",function(a){u=!0;k=a.clientX;l=a.clientY;d.style.cursor="grabbing";v&&(m.x=r((k-d.width/2+g.x)*q,2),m.y=r((l-d.height/2+g.y)*q,2),v=!1)});d.addEventListener("mousemove",function(a){if(u){const c=a.clientY-l;g.x+=-(a.clientX-k);g.y+=-c}k=a.clientX;l=a.clientY});d.addEventListener("mouseup",function(a){u=!1;k=a.clientX;l=a.clientY;d.style.cursor="grab"});window.addEventListener("wheel",function(a){var c=
.1*f;0<=a.wheelDelta&&10>f?f+=c:.15<f&&(f-=c);.15>=f?f=.16:10<=f?f=9.99:(q=1/f,g.x+=(k-d.width/2)*c,g.y+=(l-d.height/2)*c)});(function(){for(const a of A){const c={h:new Image,origin:a.origin,scale:a.scale};c.h.src=a.path;c.h.addEventListener("load",function(){console.log("Loaded image!")});y.push(c)}})();document.querySelector("#al").addEventListener("click",function(){const a=prompt("Enter you furnace name: ");alert("Click on a point where you want to set your location.");d.style.cursor="pointer";
v=!0;m.g=a})}})();