'use strict';(function(r,M,G){function H(b,c){c=10**c;return Math.round(b*c)/c}function z(b,c,e){if(!(0>=e.length)){a.beginPath();var h=0,d;for(d of e)0==h?a.moveTo(d[0]+b,d[1]+c):a.lineTo(d[0]+b,d[1]+c),h++;a.lineTo(e[0][0]+b,e[0][1]+c);a.closePath()}}function I(b,c,e,h){a.lineWidth=3;a.strokeStyle="#000";a.beginPath();a.arc(b,c,7,0,2*Math.PI,!1);a.stroke();a.fill();if(e){a.font="15px Arial";e=a.measureText(h.g||"").width;e+=10;a.fillStyle="#fff";const d=.5*e;b=b-d-3.5;c-=48;a.fillRect(b,c+1,e,22);
a.lineWidth=0;z(b+(d-3.5),c+22,[[0,0],[10,0],[5,10]]);a.fill();a.fillStyle="#000";a.fillText(h.g||"",b+5,c+2+11+2)}}function t(b,c){return{x:(b-m.x)*k+f.width/2,y:(c-m.y)*k+f.height/2}}function A(b,c){return{x:(b-f.width/2)*x+m.x,y:(c-f.height/2)*x+m.y}}const N=[{path:"map/mapmain.png",origin:{x:0,y:0},scale:1},{path:"map/mapexp2.png",origin:{x:-632,y:-213},scale:1.12},{path:"map/mapexp3.png",origin:{x:672,y:-217},scale:1.023},{path:"map/mapexp4.png",origin:{x:30,y:-675},scale:1},{path:"map/mapexp5.png",
origin:{x:-576,y:289},scale:.5},{path:"map/mapexp6.png",origin:{x:-821,y:60},scale:1}],O=[{x:70,y:17,g:"furnacejesus"},{x:53,y:-28,g:"ilovefurnaces"},{x:-10,y:-97,g:"furnacemarx"},{x:109,y:119,g:"comradefurnace",i:!0},{x:-21,y:60,g:"F.P.D",j:!0},{x:-126,y:26,g:"capitalistfurnace"},{x:-122,y:-105,g:"invertedfurnace"},{x:-195,y:-34,g:"americanfurnace"},{x:-330,y:-108,g:"anvilleader"},{x:-470,y:-109,g:"i_eat_wii"},{x:-464,y:-183,g:"i_like_wii"},{x:-361,y:-263,g:"eminem_wii"},{x:-89,y:-221,g:"freezerpresident",
i:!0},{x:64,y:-174,g:"fakefurnace"},{x:84,y:-108,g:"comicalylargefreezer"},{x:222,y:-64,g:"furnacekiller"},{x:199,y:35,g:"ikillfurnacesforfun"},{x:348,y:4,g:"antifurnacegroup"},{x:380,y:-92,g:"femboyfurnace"},{x:197,y:-146,g:"kawaiifurnace",i:!0},{x:201,y:260,g:"handsomefurnace"},{x:-56,y:382,g:"ThaiFurnace",j:!0},{x:-167,y:376,g:"iFurnace",j:!0},{x:-90,y:120,g:"iunfuckfurnaces"},{x:226,y:127,g:"iwillendfurnaces"},{x:135,y:-200,g:"metalfurnace"},{x:-298,y:114,g:"dragonfurnace"},{x:96,y:-309,g:"freezersorcerer"},
{x:-599,y:326,g:"eldritchfurnace"},{x:-824,y:85,g:"upsidedownfurnace",i:!0},{x:414,y:-48,g:"furnacekitty"},{x:-266,y:-476,u:"idownloadfurnaces"}],P=[{x:-128,y:81,name:"West Burnin"},{x:22,y:-50,name:"East Burnin"},{x:-296,y:-184,name:"Forgehelm"},{x:-424,y:-228,name:"Wiiland"},{x:-21,y:-233,name:"Glacia"},{x:10,y:-332,name:"Coald Mines"},{x:282,y:7,name:"Pyraxis"},{x:202,y:-174,name:"Ignicis"},{x:0,y:-480,name:"Unclaimed Territories"},{x:-595,y:298,name:"Eldritch Tower"},{x:-834,y:49,name:"Furnacestralia"},
{x:-1E4,y:-1E4,name:"Nothing here..."},{x:-2E4,y:-2E4,name:"Try to guess my main"},{x:-3E4,y:-3E4,name:"Have a guess?"},{x:-4E4,y:-4E4,name:"ok."},{x:-5E4,y:-5E4,name:"it is..."}],Q=[{x:-799,y:44,name:"New Furnace",m:1,l:!0},{x:-538,y:-281,name:"West Camp 1",m:1},{x:-265,y:-472,name:"Download Village",m:1}],R=[{x:-522,y:-312,name:"West territories",size:10,o:60},{x:-411,y:-700,name:"Freezepoint Sea",size:14,o:-15},{x:-245,y:-482,name:"Charcoal Lake",size:7}];"beta 1.1"!=G.getItem("last_update")&&
alert("New Version beta 1.1! This update fixed map panning / zoom and added the ability to display towns and terrain labels for things suck as territories and oceans.");G.setItem("last_update","beta 1.1");const f=r.querySelector("#c"),S=r.querySelector(".cursor-pos"),J=r.querySelector("#fsi");if(null==f)console.error("Failed to get canvas!");else{var a=f.getContext("2d"),m={x:0,y:0},k=1,x=1/k,B=!1,p=0,q=0,K=[],u={x:null,y:null},C=!1,D=[],E=!1;r.querySelector("#cr").addEventListener("click",function(){E=
!0;D=[]});r.querySelector("#se").addEventListener("input",function(){r.querySelector(".editor-box").style.display=this.checked?"block":"none"});var v={x:0,y:0};setInterval(function(){a.translate(.5,.5);f.width=r.documentElement.clientWidth;f.height=r.documentElement.clientHeight;f.style.position="absolute";f.style.left="0";f.style.top="0";a.fillStyle="#C3E7FB";a.fillRect(0,0,f.width,f.height);for(var b of K){var c=b.h.width*b.scale,e=b.h.height*b.scale,h=t(b.origin.x-c/2,b.origin.y-e/2);a.drawImage(b.h,
h.x,h.y,c*k,e*k)}S.innerText="Cursor Position: ("+H(v.x,2)+", "+H(v.y,2)+")";for(var d of R)a.font=`bold ${d.size*k}px Arial`,b=a.measureText(d.name),c=b.actualBoundingBoxAscent+b.actualBoundingBoxDescent,a.fillStyle="#000",a.globalAlpha=.25,e=t(d.x,d.y),a.save(),a.translate(e.x,e.y),a.rotate(d.o*Math.PI/180),a.fillText(d.name,-b.width/2,-c/2),a.restore(),a.globalAlpha=1;for(var g of Q){d=t(g.x,g.y);a:{b=[10**6,1E5,5E4,1E4];c=4;for(var y of b){if(g.m>=b[c])break a;c--}c=0}b=10*(1+.2*c);if(g.l||!(x/
10>c/4+.25)){if(g.l)c=4,b=18,a.strokeStyle="#000",a.fillStyle="#fff",e=b/5,h=b/4,z(d.x,d.y,[[2*h,0*e],[3*h,2*e],[4*h,2*e],[3*h,3*e],[4*h,5*e],[2*h,4*e],[0*h,5*e],[1*h,3*e],[0*h,2*e],[1*h,2*e]]),a.lineWidth=2,a.fill(),a.stroke();else switch(c){case 0:a.fillStyle="#000";a.fillRect(d.x,d.y,b,b);break;case 1:a.fillStyle="#000";a.s();a.arc(d.x,d.y,b,0,2*Math.PI);a.fill();break;case 2:a.strokeStyle="#000";a.fillStyle="#fff";a.s();a.arc(d.x,d.y,b,0,2*Math.PI);a.lineWidth=2;a.fill();a.stroke();break;case 3:a.fillStyle=
"#000",e=[[.5*b,0],[b,b],[0,b]],a.strokeStyle="#000",a.fillStyle="#fff",z(d.x,d.y,e),a.lineWidth=2,a.fill(),a.stroke()}!g.l&&x/10>c/4+.025||(a.fillStyle="#000",a.strokeStyle="#fff",c=12*(1+.1*c),a.font=`${c}px Arial`,a.strokeText(g.name,d.x+b+5,d.y+c),a.fillText(g.name,d.x+b+5,d.y+c))}}for(var l of P)g=l.name||"???",a.font="25px Arial",a.fillStyle="#000",a.strokeStyle="#fff",a.lineWidth=3,y=t(l.x-.5*a.measureText(g).width,l.y),a.strokeText(g,y.x,y.y),a.fillText(g,y.x,y.y);null!=u.x&&null!=u.y&&(a.strokeStyle=
"#000",a.fillStyle="#f00",l=t(u.x-3.5,u.y-3.5),I(l.x,l.y,J.checked||7>Math.sqrt((p-l.x)**2+(q-l.y)**2),{g:(u.j?"":"u/")+u.g}));for(var n of O)l=t(n.x-2.5,n.y-2.5),g=5>Math.sqrt((p-l.x)**2+(q-l.y)**2),a.fillStyle=n.i?g?"#ec0":"#fe0":g?"#090":"#0f0",I(l.x,l.y,J.checked||g,{g:(n.j?"":"u/")+n.g});if(E&&(n=D,!(0>=n.length))){l=0;a.beginPath();for(var w of n)if(g=t(w.x,w.y),"object"==typeof g){switch(l){case 0:a.moveTo(g.x,g.y);break;default:a.lineTo(g.x,g.y)}l++}w=t(n[0].x,n[0].y);a.lineTo(w.x,w.y);a.strokeStyle=
"#0a0";a.fillStyle="#0f0";a.lineWidth=3;a.lineCap="round";a.stroke();a.globalAlpha=.25;a.fill();a.closePath();a.globalAlpha=1;a.fillStyle="#0b0";for(const L of n)w=t(L.x,L.y),a.beginPath(),a.arc(w.x,w.y,5,0,2*Math.PI,!1),a.fill()}},1E3/60);f.style.cursor="grab";var F=!1;f.addEventListener("keydown",function(b){switch(b.key.toLowerCase()){case "shift":F=!0}});f.addEventListener("keyup",function(b){switch(b.key.toLowerCase()){case "shift":F=!1}});f.addEventListener("mousedown",function(b){p=b.clientX;
q=b.clientY;v=A(p,q);f.style.cursor="grabbing";E&&!F?D.push({x:v.x,y:v.y}):B=!0;C&&(u=v,C=!1)});f.addEventListener("mousemove",function(b){if(B){const c=b.clientY-q;m.x+=-(b.clientX-p)*x;m.y+=-c*x}p=b.clientX;q=b.clientY;v=A(p,q)});f.addEventListener("mouseup",function(b){B=!1;p=b.clientX;q=b.clientY;v=A(p,q);f.style.cursor="grab"});M.addEventListener("wheel",function(b){var c=.1*k;0<=b.wheelDelta&&10>k?k+=c:.15<k&&(k+=-1*c);x=1/k;.15>=k?k=.16:10<=k?k=9.99:(m.x+=.1*(p-f.width/2),m.y+=.1*(q-f.height/
2))});(function(){for(const b of N){const c={h:new Image,origin:b.origin,scale:b.scale};c.h.src=b.path;c.h.addEventListener("load",function(){console.log("Loaded image!")});K.push(c)}})();r.querySelector("#al").addEventListener("click",function(){const b=prompt("Enter you furnace name: ");alert("Click on a point where you want to set your location.");f.style.cursor="pointer";C=!0;u.g=b})}})(document,window,localStorage);
